module.exports = {
  apps: [
    {
      name: "banteragent",
      script: "npm",
      args: "run start",
      cwd: "/home/pi/banteragent",
      interpreter: "none",
      restart_delay: 5000,
      max_restarts: 20,
      min_uptime: "10s",
      env: { NODE_ENV: "production" },
      autorestart: true,
      out_file: "/home/pi/logs/banteragent-out.log",
      error_file: "/home/pi/logs/banteragent-err.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "bug-watcher",
      script: "/home/pi/scripts/bug-watcher.sh",
      interpreter: "bash",
      autorestart: true,
      restart_delay: 3000,
      out_file: "/home/pi/logs/bug-watcher-out.log",
      error_file: "/home/pi/logs/bug-watcher-err.log",
      time: true,
    },
    {
      name: "battery-monitor",
      script: "/home/pi/robot/battery_monitor.py",
      interpreter: "python3",
      autorestart: true,
      restart_delay: 10000,
      out_file: "/home/pi/logs/battery-monitor-out.log",
      error_file: "/home/pi/logs/battery-monitor-err.log",
      time: true,
    },
  ],
};
